config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/flats', to: 'flats#index', as: :flats
  get '/flats/:id', to: 'flats#detail', as: :flat
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flats

  def index
  end

  def detail
    @flat = @flats.find do |flat|
      flat["id"] == params[:id].to_i
    end
  end

  private
    def set_flats
      url = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json"
      data = RestClient.get(url)
      @flats = JSON.parse(data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/detail.html.erb
<h1>
  <%= @flat["name"] %>
</h1>

app/views/flats/index.html.erb
<h1>Flats</h1>
<% @flats.each do |flat| %>
  <%= link_to flat_path(flat["id"]) do %>
    <div>
      <%= flat["name"] %>
      <img src="<%= flat["imageUrl"] %>" style="width:400px; height: 200px; object-fit: cover;"/>
      <%= flat["price"] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>